version: '3.8'

services:
  loadtest-master:
    build:
      context: .
      dockerfile: deployments/master.dockerfile
    image: jake4/loadtest-master:latest
    environment:
      REST_PORT: 8080
      RABBIT_HOST: "loadtest-master"
      RABBIT_PORT: 5672
      RABBIT_USER: guest
      RABBIT_PASS: guest
    ports:
      - "8080:8080" # REST API
      - "15672:15672" # For RabbitMQ management
      - "5672:5672" # RabbitMQ server
    volumes:
      - ./.env:/app/.env
      - loadtest-db:/app/db/load_testing.db
    healthcheck:
      test: rabbitmq-diagnostics -q status && rabbitmq-diagnostics -q check_local_alarms
      interval: 10s
      timeout: 5s
      retries: 5
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: '1'
          memory: 1G

  loadtest-worker:
    build:
      context: .
      dockerfile: deployments/worker.dockerfile
    image: jake4/loadtest-worker:latest
    environment:
      REST_PORT: 8080
      RABBIT_HOST: "loadtest-master"
      RABBIT_PORT: 5672
      RABBIT_USER: guest
      RABBIT_PASS: guest
    volumes:
      - ./.env:/app/.env
    depends_on:
      loadtest-master:
        condition: service_healthy
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 256M
volumes:
  loadtest-db: {}