name: Go Test

on:
  workflow_run:
    workflows: ["Deploy to Digital Ocean Kubernetes"]
    types:
      - completed
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Set up Go 1.21.5
      uses: actions/setup-go@v5.0.0
      with:
        go-version: 1.21.5

    - name: Test
      run: go test ./tests/...